apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-app-config
  namespace: default
  resourceVersion: "1"
data:
  MONGO_HOST: {{ .Release.Name }}-mongodb
  MONGO_PORT: "27017"
  MONGO_COLLECTION: otus