apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-app-config
  namespace: default
  resourceVersion: "1"
data:
  MONGO_HOST: {{ .Release.Name }}-mongodb
  MONGO_PORT: {{ .Values.mongodb.service.port | quote}}
  MONGO_COLLECTION: {{ .Values.mongodb.mongodbDatabase }}