apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
  resourceVersion: "1"
type: Opaque
data:
  MONGO_NAME: {{ .Values.mongodb.mongodbUsername | b64enc }}
  MONGO_PASS: {{ .Values.mongodb.mongodbPassword | b64enc }}