apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  namespace: {{ .Release.Namespace }}
  labels:
    service: zipkin-service
spec:
  selector:
    app: zipkin
  ports:
  - name: api
    port: 9411
    targetPort: 9411