nginx-ingress:
  controller:
    kind: DaemonSet
    reportNodeInternalIp: true
    daemonset:
      useHostPort: true
      hostPorts:
        http: 80
        https: 443
    service:
      type: NodePort
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

mongodb:
  mongodbRootPassword: root
  mongodbUsername: otus
  mongodbPassword: otus
  mongodbDatabase: otus
  service:
    port: 27017

prometheus-mongodb-exporter:
  mongodb:
    uri: mongodb://root:root@otus-mongodb:27017

prometheus-operator:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorNamespaceSelector: {}

  grafana:
    admin:
      existingSecret: grafana-login-secrets
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/use-regex: "true"
      path: /grafana/?(.*)
      hosts:
        - arch.homework
    sidecar:
      dashboards:
        enabled: true
        label:  grafana-dashboard
    grafana.ini:
      server:
        root_url: http://localhost:3000/grafana

redis:
  cluster:
    enabled: false
    slaveCount: 0
  master:
    persistence:
      enabled: false
    resources:
      limits:
        memory: 512Mi
  password: qwerty123
  configmap: |-
    # 5242880‬ == 5Mb
    #maxmemory 5242880‬
    #maxmemory-policy noeviction
    maxmemory-policy allkeys-lru

app:
  image:  makhnevvitalik/otus-task6:1.0.12
  cache:
    enabled: false
    ttl: 1h
