apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
  namespace: default
  resourceVersion: "1"
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=