{
 "title": "Otus",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Latency 0.5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (method, le, uri) (rate(user_requests_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.5 {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (rate(user_requests_seconds_count[1m]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Latency 0.9",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (method, le, uri) (rate(user_requests_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.9 {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(user_requests_seconds_count{status=~\"5..\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency 0.99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (method, le, uri) (rate(user_requests_seconds_bucket[1m]))) * 1000",
     "legendFormat": " 0.99 {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "App Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"otus\", pod=~'otus-app-.*'}",
     "legendFormat": "Pod {{pod}}"
    }
   ]
  },
  {
   "title": "Latency Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (method, le, uri) (rate(user_requests_seconds_bucket[1m]))) * 1000",
     "legendFormat": "Max {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "App CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 21 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_user_seconds_total{container=\"otus\", pod=~\"otus-app-.*\"}[30s])) without (cpu) * 100",
     "legendFormat": "Pod {{pod}}"
    }
   ]
  },
  {
   "title": "Mongo Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "mongodb_memory", "legendFormat": "Memory: {{type}}" }
   ]
  },
  {
   "title": "Nginx Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (ingress, le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~'otus-app-.*'}[1m]))) * 1000",
     "legendFormat": "0.5 {{ingress}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (ingress, le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~'otus-app-.*'}[1m]))) * 1000",
     "legendFormat": "0.95 {{ingress}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (ingress, le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~'otus-app-.*'}[1m]))) * 1000",
     "legendFormat": "0.99 {{ingress}}"
    },
    {
     "expr": "histogram_quantile(1, sum by (ingress, le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~'otus-app-.*'}[1m]))) * 1000",
     "legendFormat": "Max {{ingress}}"
    }
   ]
  },
  {
   "title": "Nginx RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ingress) (rate(nginx_ingress_controller_request_duration_seconds_count{ingress=~'otus-app-.*'}[1m]))",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Nginx Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ingress) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~'otus-app-.*', status=~\"5..\"}[1m]))",
     "legendFormat": "{{ingress}} 5xx"
    }
   ]
  }
 ]
}