nginx-ingress:
  controller:
    kind: DaemonSet
    reportNodeInternalIp: true
    daemonset:
      useHostPort: true
      hostPorts:
        http: 80
        https: 443
    service:
      type: NodePort
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

oauth2-proxy:
  config:
    clientID: 4092cfd8593a4a19f868
    clientSecret: cb698dc32fe7072a1f6968261d92c497a9659a89
    cookieSecret: R6xuJLFvO3vStPIgNpi0Sg==
  extraArgs:
    provider: github
    email-domain: "*"
    whitelist-domain: "github.com"
    upstream: file:///dev/null
    cookie-name: oauth2
    set-xauthrequest: true
  service:
    port: 4180
  ingress:
    enabled: true
    hosts: ["arch.homework"]
    path: /oauth2

mongodb:
  replicaSet:
    enabled: true
    key: "1234567890"
  mongodbRootPassword: root
  mongodbUsername: otus
  mongodbPassword: otus
  mongodbDatabase: otus
  service:
    port: 27017
  resources:
    limits:
      memory: "512Mi"
  resourcesArbiter:
    limits:
      memory: "512Mi"

prometheus-mongodb-exporter:
  mongodb:
    uri: mongodb://root:root@otus-mongodb:27017

prometheus-rabbitmq-exporter:
  prometheus:
    monitor:
      enabled: true
  rabbitmq:
    url: http://otus-rabbitmq:15672
    user: otus
    password: otus

prometheus-operator:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorNamespaceSelector: {}

  grafana:
    admin:
      existingSecret: grafana-login-secrets
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/use-regex: "true"
      path: /grafana/?(.*)
      hosts:
        - arch.homework
    sidecar:
      dashboards:
        enabled: true
        label:  grafana-dashboard
    grafana.ini:
      server:
        root_url: http://localhost:3000/grafana

redis:
  cluster:
    enabled: false
    slaveCount: 0
  master:
    persistence:
      enabled: false
    resources:
      limits:
        memory: "256Mi"
  password: qwerty123
  configmap: |-
    maxmemory-policy allkeys-lru

rabbitmq:
  auth:
    username: otus
    password: otus

app:
  auth:
    enabled: true
  cache:
    enabled: true
    ttl: 1h

order:
  image: makhnevvitalik/otus-order:1.0.5
warehouse:
  image: makhnevvitalik/otus-warehouse:1.0.2
delivery:
  image: makhnevvitalik/otus-delivery:1.0.2
payment:
  image: makhnevvitalik/otus-payment:1.0.2
product:
  image: makhnevvitalik/otus-product:1.0.4
customer:
  image: makhnevvitalik/otus-customer:1.0.3