apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
  namespace: default
  resourceVersion: "1"
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.initDbRoot | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.initDbPass | b64enc }}