nginx-ingress:
  controller:
    kind: DaemonSet
    reportNodeInternalIp: true
    daemonset:
      useHostPort: true
      hostPorts:
        http: 80
        https: 443
    service:
      type: NodePort
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

mongodb:
  mongodbRootPassword: root
  mongodbUsername: otus
  mongodbPassword: otus
  mongodbDatabase: otus
  service:
    port: 27017

prometheus-mongodb-exporter:
  mongodb:
    uri: mongodb://root:root@otus-mongodb:27017

prometheus-operator:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorNamespaceSelector: {}

  grafana:
    admin:
      existingSecret: grafana-login-secrets
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/use-regex: "true"
      path: /grafana/?(.*)
      hosts:
        - arch.homework
    sidecar:
      dashboards:
        enabled: true
        label:  grafana-dashboard
    grafana.ini:
      server:
        root_url: http://localhost:3000/grafana