apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus-app
  template:
    metadata:
      labels:
        app: otus-app
    spec:
      containers:
      - name: otus
        image: {{ .Values.app.image }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-Xmx550m -XX:MaxMetaspaceSize=135m -XX:ReservedCodeCacheSize=100m -Xss256k -XX:MaxDirectMemorySize=10m"
        envFrom:
        - configMapRef:
            name: mongo-app-config
        - secretRef:
            name: mongo-app-secrets
        ports:
        - containerPort: 8000
          name: app-port
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            port: app-port
            path: /actuator/health
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 30
        resources:
          limits:
            memory: "1024Mi"
