apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-app-config
  namespace: default
  resourceVersion: "1"
data:
  MONGO_HOST: {{ .Values.mongo.mongoHost }}
  MONGO_PORT: {{ .Values.mongo.mongoPort | quote }}
  MONGO_COLLECTION: {{ .Values.mongoAppDb }}