apiVersion: v1
kind: Secret
metadata:
  name: mongo-app-secrets
  namespace: default
  resourceVersion: "1"
type: Opaque
data:
  MONGO_NAME: {{ .Values.mongoUser | b64enc }}
  MONGO_PASS: {{ .Values.mongoPass | b64enc }}