apiVersion: batch/v1
kind: Job
metadata:
  name: otus-generator-job
spec:
  template:
    spec:
      containers:
      - name: otus-generator1
        image: makhnevvitalik/otus-task6:1.0.10
        env:
          - name: GENERATOR_ENABLED
            value: "true"
          - name: GENERATOR_COUNT
            value: "500000"
          - name: SERVER_PORT
            value: "0"
          - name: JAVA_TOOL_OPTIONS
            value: "-Xmx128m"
        envFrom:
        - configMapRef:
            name: mongo-app-config
        - secretRef:
            name: mongo-app-secrets
      - name: otus-generator2
        image: makhnevvitalik/otus-task6:1.0.10
        env:
          - name: GENERATOR_ENABLED
            value: "true"
          - name: GENERATOR_COUNT
            value: "500000"
          - name: SERVER_PORT
            value: "0"
          - name: JAVA_TOOL_OPTIONS
            value: "-Xmx128m"
        envFrom:
        - configMapRef:
            name: mongo-app-config
        - secretRef:
            name: mongo-app-secrets

      restartPolicy: Never
  backoffLimit: 3
